# Generated by Django 3.1.4 on 2020-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=320)),
                ('cred', models.CharField(max_length=200)),
                ('credUpdated', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
