# Generated by Django 3.1.4 on 2020-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='prescribed',
            new_name='dosage',
        ),
        migrations.AddField(
            model_name='quantity',
            name='period',
            field=models.SmallIntegerField(default=0),
        ),
    ]
