# Generated by Django 3.1.4 on 2020-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_auto_20201216_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='perDay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
