# Generated by Django 3.1.4 on 2020-12-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_quantity_perday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='dosage',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='inStock',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='period',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
