# Generated by Django 3.1.4 on 2020-12-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_auto_20201216_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='rawStock',
            field=models.SmallIntegerField(default=0),
        ),
    ]
